export const store={sessions:{},active:"",servers:[],config:{},flow:{stages:[],edges:[]},tools:[]};
const listeners=new Set();
export function subscribe(fn){listeners.add(fn);fn(store,{type:"init"});return()=>listeners.delete(fn)}
function notify(event){for(const fn of listeners)fn(store,event)}
function session(event){return store.sessions[event.session_id]}
function mergeRun(target,patch){target.run=Object.assign({},target.run,patch)}
export function reduce(event){const data=event.data||{};if(event.type==="snapshot"){const active=store.active;Object.assign(store,data);store.active=store.sessions[active]?active:Object.keys(store.sessions)[0]||"";for(const value of Object.values(store.sessions))hydrate(value);notify(event);return}
  const target=session(event);switch(event.type){
  case"session.created":store.sessions[data.session.id]=data.session;hydrate(data.session);if(!store.active)store.active=data.session.id;break;
  case"session.renamed":if(target)target.label=data.label;break;case"session.reset":if(target){target.messages=[];target.timeline=[];mergeRun(target,{status:"idle",turn:0,partial:""})}break;case"session.closed":delete store.sessions[data.session_id];if(store.active===data.session_id)store.active=Object.keys(store.sessions)[0]||"";break;
  case"server.probed":{const p=store.servers.find(x=>x.id===data.server_id);if(p)p.capabilities=data.capabilities;break}case"config.changed":store.config=data.config;store.servers=data.config.servers||store.servers;break;case"error":store.error=data;break;
  case"run.queued":if(target)mergeRun(target,{status:"queued",run_id:data.run_id,queue_position:data.position});break;case"run.started":if(target){mergeRun(target,{status:"running",run_id:data.run_id,turn:0,queue_position:0});target._lastStop=""}break;case"run.stopped":if(target){mergeRun(target,{status:"idle",partial:""});target._lastStop=data.reason;target._stage="wait_user"}break;
  case"stage":if(target){target._stage=data.state==="enter"?data.stage:target._stage;target._stageState=data.state;if(data.state==="enter"&&data.stage==="assemble")target._completedStages=[];else if(data.state==="exit"&&!target._completedStages.includes(data.stage))target._completedStages.push(data.stage);target.run.turn=data.turn}break;
  case"model.progress":if(target)target._progress=data;break;case"model.delta":if(target&&data.kind==="content")target.run.partial=(target.run.partial||"")+data.text;break;case"model.response":if(target){target._timings=data.timings;target.run.partial=""}break;
  case"tool.call":if(target)target._activeTool=data.name;break;case"tool.result":if(target){target._activeTool="";const tool=target.tools.find(x=>x.name===data.name);if(tool)tool.calls=(tool.calls||0)+1}break;case"tool.toggled":if(target){const tool=target.tools.find(x=>x.name===data.name);if(tool)tool.enabled=data.enabled}break;
  case"message.appended":if(target)target.messages.push(data.message);break;case"message.updated":if(target){const m=target.messages.find(x=>x.id===data.id);if(m)Object.assign(m,data.patch)}break;case"message.queued":if(target)target.queued_messages=(target.queued_messages||0)+1;break;case"budget":if(target)target.budget=data;break;
  case"approval.required":case"approval.decided":case"cycle.detected":case"workspace.conflict":case"compaction":case"memory.noted":if(target){target._events=target._events||[];target._events.push(event)}break}
  if(target){target.timeline=target.timeline||[];target.timeline.push(event);if(target.timeline.length>200)target.timeline=target.timeline.slice(-200)}notify(event)}
function hydrate(value){value.messages=value.messages||[];value.timeline=value.timeline||[];value.tools=value.tools||[];value._stage=value._stage||"";value._completedStages=value._completedStages||[]}
export function setActive(id){if(store.sessions[id]){store.active=id;notify({type:"active.changed",data:{id}})}}
export async function api(path,body,method="POST"){const options={method,headers:{}};if(body!==undefined){options.headers["Content-Type"]="application/json";options.body=JSON.stringify(body)}const response=await fetch(path,options);const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||`HTTP ${response.status}`);return data}
const connection=document.getElementById("connection");let reconnected=false;const source=new EventSource("/api/events");source.onopen=()=>{if(reconnected&&connection){connection.textContent="reconnected";connection.className="";setTimeout(()=>{connection.textContent=""},3000)}reconnected=true};source.onerror=()=>{if(connection){connection.textContent="connection lost — retrying";connection.className="alarm"}};source.onmessage=event=>reduce(JSON.parse(event.data));for(const type of ["snapshot","session.created","session.renamed","session.reset","session.closed","server.probed","config.changed","error","run.queued","run.started","run.stopped","stage","model.request","model.progress","model.delta","model.response","tool.call","tool.result","tool.toggled","message.appended","message.updated","message.queued","budget","approval.required","approval.decided","cycle.detected","workspace.conflict","compaction","memory.noted"]){source.addEventListener(type,event=>reduce(JSON.parse(event.data)))}
